version: "3.4"

services:  
        redis:
                image: redis:latest
                hostname: redis

        web:
                image: raphaelrobidas/calcus:latest
                restart: always
                hostname: web
                user: "${UID}:${GID}"
                command: ./scripts/run_web.sh
                expose:
                        - 8000
                volumes:
                        - ./scr:/calcus/scr
                        - ./keys:/calcus/keys
                        - ./backups:/calcus/backups
                        - ./logs:/calcus/logs
                        - ./frontend/migrations:/calcus/frontend/migrations
                        - ./scripts:/calcus/scripts
                links:
                        - redis
                env_file:
                        - ./.env
                depends_on:
                        - postgres
                environment:
                        - GUNICORN_TIMEOUT=30

        nginx:
                image: nginx:latest
                ports:
                        - "8080:8080"
                volumes:
                        - ./docker/nginx/:/etc/nginx/conf.d
                        - ./static:/static
                        - .:/calcus
                depends_on: 
                        - web        
        celery_main:
                image: raphaelrobidas/calcus:latest
                user: calcus
                command: ./scripts/run_celery_main.sh
                volumes:
                        - ./scr:/calcus/scr
                        - ./keys:/calcus/keys
                        - ./backups:/calcus/backups
                env_file:
                        - ./.env
                links:
                        - redis
                depends_on:
                        - redis
        celery_comp:
                image: raphaelrobidas/calcus:latest
                user: calcus
                command: ./scripts/run_celery_comp.sh
                volumes:
                        - ./scr:/calcus/scr
                        - ./keys:/calcus/keys
                env_file:
                        - ./.env
                links:
                        - redis
                depends_on:
                        - redis
        cluster:
                image: raphaelrobidas/calcus:latest
                user: "${UID}:${GID}"
                command: ./scripts/run_cluster_daemon.sh
                env_file:
                        - ./.env
                volumes:
                        - ./scr:/calcus/scr
                        - ./keys:/calcus/keys
                links:
                        - web
                depends_on:
                        - redis
        postgres:
                image: postgres:11-bullseye
                restart: always
                user: "${UID}:${GID}"
                volumes:
                        - ./data:/var/lib/postgresql/data/:rw
                        - ./data/postgresql.conf:/var/lib/postgresql/data/postgresql.conf:r
                        - ./backups:/calcus/backups
                        - ./logs:/calcus/logs
                env_file:
                        - ./.env
                environment:
                        - PGDATA=./var/lib/postgresql/data/
                        - POSTGRES_USER=calcus
                        - POSTGRES_DB=calcus


